# Site settings
title: MJT Construction Ltd.
email: mike@mjtconstructionltd.com
description: >
  Site description.
baseurl: ""
url: "http://mjtconstructionltd.com"

# Build settings
markdown: kramdown
