# Site settings
title: MJT Construction Ltd.
email: mike@mjtconstructionltd.com
description: >
  MJT Construction Ltd. builder norfolk residential commercial
  property repairs alterations maintenance
baseurl: ""
url: "http://mjtconstructionltd.com"

exclude: [README.md]

# Build settings
markdown: kramdown
