# Site settings
title: MJT Construction Ltd.
email: mike@mjtconstructionltd.com
description: >
  MJT Construction Ltd. are specialists in commercial and
  residential property repairs, alterations and maintenance.
baseurl: ""
url: "http://mjtconstructionltd.com"

exclude: [README.md]

# Build settings
markdown: kramdown
